spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: augmaticdisport22-
    url: jdbc:postgresql://cjportillo89.cwrr2qklkyum.us-east-2.rds.amazonaws.com:5432/Library
    username: cjportillo89
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090